version = 1

test_patterns = [
    "*/test/**",
    "**/*_test.go"
]

exclude_patterns = [
    "docs",
    "assets",
    "tmp",
    "build"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/cognitivehacker/kongame"]

[[transformers]]
name = "gofmt"
enabled = true
